"use client";

import React, { useEffect, useRef, useState } from "react";
import { ExternalLink } from "lucide-react";

const videos = [
  "/videos/annimate.mp4",
  "/videos/skiing.mp4",
  "/videos/bride.mp4",
  "/videos/eyes.mp4",
  "/videos/grandama sing.mp4",
  "/videos/girl.mp4",
  "/videos/advertise.mp4",
  "/videos/celebrate.mp4",
];

function VideoItem({ src }: { src: string }) {
  const ref = useRef<HTMLVideoElement>(null);
  const [isMuted, setIsMuted] = useState(false);

  const tryPlayWithSound = async () => {
    const el = ref.current;
    if (!el) return;
    el.muted = false;
    el.volume = 1;
    el.currentTime = 0;
    try {
      await el.play();
      setIsMuted(false);
    } catch {
      // Autoplay with sound blocked: fallback to muted autoplay
      el.muted = true;
      setIsMuted(true);
      try { await el.play(); } catch {}
    }
  };

  const pauseAndReset = () => {
    const el = ref.current;
    if (!el) return;
    el.pause();
    el.currentTime = 0;
  };

  const toggleMute = async () => {
    const el = ref.current;
    if (!el) return;
    // If paused, prefer playing with sound; fallback to muted if blocked
    if (el.paused) {
      el.muted = false;
      try {
        await el.play();
        setIsMuted(false);
        return;
      } catch {}
      el.muted = true;
      setIsMuted(true);
      try { await el.play(); } catch {}
      return;
    }
    // If playing, toggle mute without pausing
    if (el.muted) {
      el.muted = false;
      setIsMuted(false);
      try { await el.play(); } catch {}
    } else {
      el.muted = true;
      setIsMuted(true);
      try { await el.play(); } catch {}
    }
  };

  const unmuteOnClick = async () => {
    const el = ref.current;
    if (!el) return;
    if (el.muted) {
      el.muted = false;
      setIsMuted(false);
      try { await el.play(); } catch {}
    }
  };

  return (
    <div className="mb-4 rounded-xl overflow-hidden border bg-black/5 dark:bg-white/5 break-inside-avoid relative">
      <video
        ref={ref}
        src={encodeURI(src)}
        playsInline
        loop
        preload="metadata"
        muted={isMuted}
        tabIndex={0}
        className="w-full h-auto block transition-transform duration-200 hover:scale-[1.01]"
        onMouseEnter={tryPlayWithSound}
        onMouseLeave={pauseAndReset}
        onTouchStart={toggleMute}
        onClick={toggleMute}
        onKeyDown={(e) => { if (e.key === 'Tab') { void toggleMute(); } }}
      />
      {isMuted && (
        <button
          onClick={unmuteOnClick}
          className="absolute inset-x-0 bottom-3 mx-auto w-fit px-3 py-1.5 text-xs font-medium rounded-full bg-black/60 text-white backdrop-blur hover:bg-black/70"
        >
          Tap to unmute
        </button>
      )}
    </div>
  );
}

const DemoGallery = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;

  return (
    <section id="examples" className="py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between mb-12">
          <div>
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">
              See what our community <span className="text-primary">created</span>
            </h2>
            <p className="text-xl text-muted-foreground">Real videos generated by creators using our platform</p>
          </div>
          <button className="hidden sm:flex items-center text-primary hover:text-primary-glow font-medium group">
            See more
            <ExternalLink className="w-4 h-4 ml-1 group-hover:translate-x-0.5 transition-transform" />
          </button>
        </div>

        <div className="columns-1 sm:columns-2 xl:columns-3 gap-4 [column-fill:_balance]">
          {videos.map((v) => (
            <VideoItem key={v} src={v} />
          ))}
        </div>

        <div className="text-center mt-8 sm:hidden">
          <button className="text-primary hover:text-primary-glow font-medium">See more examples →</button>
        </div>
      </div>
    </section>
  );
};

export default DemoGallery;
