"use client";

import React, { useEffect, useRef, useState } from "react";
import { ExternalLink } from "lucide-react";

const videos = [
  "/videos/annimate.mp4",
  "/videos/bride.mp4",
  "/videos/eyes.mp4",
  "/videos/grandama sing.mp4",
  "/videos/girl.mp4",
  "/videos/advertise.mp4",
  "/videos/celebrate.mp4",
  "/videos/neuralMane.mp4",
  "/videos/4_2ec5d6ac08.mp4",
];

function VideoItem({ src }: { src: string }) {
  const ref = useRef<HTMLVideoElement>(null);
  const [isMuted, setIsMuted] = useState(false);
  const [hasError, setHasError] = useState(false);

  const tryPlayWithSound = async () => {
    const el = ref.current;
    if (!el) return;
    el.muted = false;
    el.volume = 1;
    el.currentTime = 0;
    try {
      await el.play();
      setIsMuted(false);
    } catch {
      // Autoplay with sound blocked: fallback to muted autoplay
      el.muted = true;
      setIsMuted(true);
      try { await el.play(); } catch {}
    }
  };

  const pauseAndReset = () => {
    const el = ref.current;
    if (!el) return;
    el.pause();
    el.currentTime = 0;
  };

  const toggleMute = async () => {
    const el = ref.current;
    if (!el) return;
    // If paused, prefer playing with sound; fallback to muted if blocked
    if (el.paused) {
      el.muted = false;
      try {
        await el.play();
        setIsMuted(false);
        return;
      } catch {}
      el.muted = true;
      setIsMuted(true);
      try { await el.play(); } catch {}
      return;
    }
    // If playing, toggle mute without pausing
    if (el.muted) {
      el.muted = false;
      setIsMuted(false);
      try { await el.play(); } catch {}
    } else {
      el.muted = true;
      setIsMuted(true);
      try { await el.play(); } catch {}
    }
  };

  const unmuteOnClick = async () => {
    const el = ref.current;
    if (!el) return;
    if (el.muted) {
      el.muted = false;
      setIsMuted(false);
      try { await el.play(); } catch {}
    }
  };

  const handleError = () => {
    setHasError(true);
  };

  if (hasError) {
    return null;
  }

  return (
    <div className="mb-4 sm:mb-6 rounded-xl overflow-hidden border border-border/50 bg-card/50 backdrop-blur-sm break-inside-avoid relative group hover:border-primary/50 transition-all duration-300 hover:shadow-lg">
      <video
        ref={ref}
        src={encodeURI(src)}
        playsInline
        loop
        preload="metadata"
        muted={isMuted}
        tabIndex={0}
        className="w-full h-auto block transition-transform duration-300 group-hover:scale-[1.02]"
        onMouseEnter={tryPlayWithSound}
        onMouseLeave={pauseAndReset}
        onTouchStart={toggleMute}
        onClick={toggleMute}
        onKeyDown={(e) => { if (e.key === 'Tab') { void toggleMute(); } }}
        onError={handleError}
      />
      {isMuted && (
        <button
          onClick={unmuteOnClick}
          className="absolute inset-x-0 bottom-4 mx-auto w-fit px-4 py-2 text-xs font-medium rounded-full bg-black/70 backdrop-blur-md text-white hover:bg-black/80 transition-colors shadow-lg"
        >
          Tap to unmute
        </button>
      )}
    </div>
  );
}

const DemoGallery = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;

  return (
    <section id="examples" className="py-24 bg-gradient-to-b from-background to-muted/20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header Section */}
        <div className="text-center mb-16">
          <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6 tracking-tight">
            See what our community <span className="text-primary">created</span>
          </h2>
          <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Real videos generated by creators using Sora 2 platform. From cinematic storytelling to creative animations, 
            discover what's possible with Sora 2 AI-powered video generation. See Sora 2 in action. Explore Sora 2 examples and start creating with Sora 2.
          </p>
        </div>

        {/* Video Gallery */}
        <div className="columns-1 sm:columns-2 xl:columns-3 gap-4 sm:gap-6 [column-fill:_balance]">
          {videos.map((v, index) => (
            <VideoItem key={`${v}-${index}`} src={v} />
          ))}
        </div>

        {/* Footer CTA */}
        <div className="text-center mt-12">
          <button 
            className="inline-flex items-center text-primary hover:text-primary/80 font-medium group transition-colors"
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          >
            <span>See more examples</span>
            <ExternalLink className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
      </div>
    </section>
  );
};

export default DemoGallery;
